export default [
    {
    ID: '1',
    nombre: 'Jose',
    tipo: '3D',
    peso: 9,
    tamanoAnillo: '8',
    tamanoPiedra: '1.3',
    material: 'oro',
    detalle: 'no tan ancho',
    empleadoAsignado: 'Josue',
    estado: "recibido",
    fecha: "20/10/2010",
    motivoDevolucion: 'no se ha devuelto',
  },
    {
    ID: '2',
    nombre: 'Jose',
    tipo: '3D',
    peso: 9,
    tamanoAnillo: '8',
    tamanoPiedra: '1.3',
    material: 'oro',
    detalle: 'no tan ancho',
    empleadoAsignado: 'Josue',
    estado: "entregado",
    fecha: "20/10/2011",
    motivoDevolucion: 'no se ha devuelto',
  }
  ]